name: Release

on:
  push:
    branches:
      - main
      - chore/fix-release-action
    paths-ignore:
      - "tickers/**"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: 1.21
      - name: Build with xgo
        uses: crazy-max/ghaction-xgo@v3
        with:
          xgo_version: latest
          go_version: 1.21.x
          pkg: cmd/quickval/
          dest: build
          prefix: quickval
          targets: linux/amd64,darwin/amd64,darwin/arm64,windows/amd64,
          v: true
          ldflags: -s -w
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - run: pnpm init && pnpm install
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache: "pnpm"
      - name: Install Dependencies
        run: pnpm install -g semantic-release @semantic-release/exec @semantic-release/git @semantic-release/github
      - name: Semantic Release
        run: pnpm dlx semantic-release --dry-run
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
