name: Update Tickers

on:
  schedule:
    - cron: "13 0 * * 1-5"
  push:
    branches:
      - main
      - ci/fix-fetch-tickers
    paths-ignore:
      - "tickers/**"

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: 1.21
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Fetch Tickers
        run: go run ./cmd/fetch_tickers/fetch_tickers.go --api-key=${{ secrets.QUICKFS_KEY }}
      - name: Commit Changes
        uses: EndBug/add-and-commit@v9
        with:
          add: tickers/*
          message: "chore: update tickers [skip ci]"
